language: python

python:
  - "2.6"
  - "2.7"
  - "3.5"
 
# command to install dependencies
install:
  - "pip install -r requirements-test.txt"
  - "pip install gevent==1.1.0"

# command to run tests
script: 
  - "flake8 --exclude=.tox,.virtualenv --ignore=E501"
  - "nosetests --with-coverage --cover-package=graphitesend"
  
after_success:
  coveralls

sudo: false
cache: pip
